### ISSUE TITLE
Show notifications of users applied/updated, donations, delivery route changed

### ISSUE THREAD

**Issue by jasonsreynolds** [freeCodeCamp/pantry-for-good#122] opened 2017-06-15 19:28 UTC

**Comment by jspaine** [comment] 2017-08-18 13:09
Currently it's set up to email the admin when a customer applies or updates their application. It would be much better with a notification system to handle these events.

Maybe users could have an array of notifications sub-documents and use a pre-save hook to push notifications to users by role?

**Comment by ronaldblanco** [comment] 2017-12-18 15:50
Hello @jspaine let me help you with this.
Give me and idea of what you are needing here.

Thanks.

**Comment by jspaine** [comment] 2017-12-18 22:20
Hi, something like the notifications on github or facebook. Some examples:
- if a user applies admins should get a notification like "user name applied as a customer"
- clicking the notification should take you to the customers application
- there should be a button to clear the notification
- if a customer changes their address or status the assigned driver should get a notification

It could get complicated but I think supporting those would be a good start.

**Comment by ronaldblanco** [comment] 2017-12-19 23:24
This notifications will be in the model, save in mongodb right??

**Comment by jspaine** [comment] 2017-12-20 13:57
Yeah

**Comment by ronaldblanco** [comment] 2017-12-26 14:42
Hola @jspaine I am having a issue at the staging branch I am not able to create a local user (for tests) it just do nothing and do not create the user.

**Comment by jspaine** [comment] 2017-12-27 18:55
Hi @ronaldblanco, how are you trying to create a user? You should be able to manually sign up at least to create users.

**Comment by ronaldblanco** [comment] 2017-12-28 15:50
I think I know what it is happening, the problem is: when the system does not create the user (possible validation problems) it does not rise any message or alert.
I did try now again benign sure to fulfill all possible validation and the user was create correctly.

**Comment by ronaldblanco** [comment] 2017-12-28 15:52
Hey @jspaine do you want me to make the pull request so you can go checking the progress of this issue?
Or, do I finish all first?

**Comment by ronaldblanco** [comment] 2017-12-28 21:24
Hey @jspaine  could you please check this gist an advice me?
https://gist.github.com/ronaldblanco/6a7a072823eef4a28ba4a7456cc093a1

<NotificationLinkItem path={notification.url} title="Notification URL" />
//Warning: Failed prop type: The prop `path` is marked as required in `NotificationLinkItem`, but its value is `undefined`.

"notification.url" it is a string for all the RFFieldGroup objects but it is constantly undefined for the link I am trying to create.
Probably this is a silly issue but I am stock on it and I do not found any difference.

Thanks.

**Comment by jspaine** [comment] 2017-12-31 14:16
What npm packages were you thinking of? 
That commit looks on the right track, I'm not back at a computer till the 3rd to have a good look though. One thing I noticed, why add links to the field group component? It's meant for form inputs.  Also not sure why you'd use redux form?

**Comment by ronaldblanco** [comment] 2018-01-02 13:22
Hello @jspaine.
I think this could be  a good option: https://www.npmjs.com/package/react-redux-notify

I am using redux form to do an notification management panel, but, in this case only to look more details of the notification like time or to delete notification from mongodb.
It is still in progress so maybe I myself (or with your suggestions) this can be modified later.

**Comment by jspaine** [comment] 2018-01-02 17:01
Those kind of flash messages are a separate issue (#154).

Ok, but I'm still not sure why you'd want to use links in an input component.

**Comment by ronaldblanco** [comment] 2018-01-02 18:01
OK, in that case I will do the pull request so you can check complete an suggest the changes.

**Closed** 2018-05-16 21:06 UTC
Labels: help wanted
